# Funciones de pérdida

Aunque hay muchas más, vamos a ver las funciones de pérdida incluidas dentro de Pytorch

## L1

```python
torch.nn.L1loss(size_average=None, reduce=None, reduction='mean')
```

Calcula el error absoluto

$ l\left(x,y\right) = \left[l_1,...,l_N\right]^T $, donde $l = \left|x_n-y_n\right|$

`reduction` usa por defecto ``'mean'``, pero puede también usar ``'sum'`` y ``'none'``. Los parámetros ``size_average`` y ``reduce`` están obsoletos y Pytorch recomienda no usarlos y solo usar ``reduction``

Cuando en ``reduction`` se usa ``'mean'`` se hace una media de todos los errores, cuando se usa ``'sum'`` se hace la suma de todos los errores y cuando se usa ``'none'`` no se hace nada

Vamos a verlo

Creamos lo que sería la predicción de la red neuronal

In [28]:
import torch

preds = torch.rand(3, 5, requires_grad=True)
preds

tensor([[0.1499, 0.7838, 0.6332, 0.4235, 0.5981],
        [0.7691, 0.4440, 0.9998, 0.1718, 0.0864],
        [0.3246, 0.6581, 0.2118, 0.6618, 0.8150]], requires_grad=True)

Creamos lo que sería la verdadera salida

In [29]:
target = torch.rand(3, 5)
target

tensor([[0.9842, 0.0592, 0.1925, 0.2206, 0.8483],
        [0.9688, 0.5489, 0.5241, 0.3715, 0.6758],
        [0.7450, 0.4149, 0.6630, 0.8465, 0.8706]])

Definimos la función de coste con `reduction` con su valor predeterminado, es decir, `mean` y comparamos lo que da la función de coste con hacer nosotros la operación que dice la teoría

In [30]:
loss = torch.nn.L1Loss(size_average=None, reduce=None, reduction='mean') # Predeterminado

loss_fn = loss(preds, target)
my_loss = abs(preds - target).mean()

loss_fn.item(), my_loss.item()

(0.3584846556186676, 0.3584846556186676)

Definimos la función de coste ahora con `reduction` con valor `sum` y comparamos lo que da la función de coste con hacer nosotros la operación que dice la teoría

In [31]:
loss = torch.nn.L1Loss(size_average=None, reduce=None, reduction='sum')

loss_fn = loss(preds, target)
my_loss = abs(preds - target).sum()

loss_fn.item(), my_loss.item()

(5.377269744873047, 5.377269744873047)

Definimos la función de coste ahora con `reduction` con valor `none` y comparamos lo que da la función de coste con hacer nosotros la operación que dice la teoría

In [32]:
loss = torch.nn.L1Loss(size_average=None, reduce=None, reduction='none')

loss_fn = loss(preds, target)
my_loss = abs(preds - target)

loss_fn, my_loss

(tensor([[0.8343, 0.7246, 0.4406, 0.2028, 0.2503],
         [0.1998, 0.1049, 0.4757, 0.1997, 0.5894],
         [0.4204, 0.2432, 0.4513, 0.1847, 0.0557]], grad_fn=<L1LossBackward0>),
 tensor([[0.8343, 0.7246, 0.4406, 0.2028, 0.2503],
         [0.1998, 0.1049, 0.4757, 0.1997, 0.5894],
         [0.4204, 0.2432, 0.4513, 0.1847, 0.0557]], grad_fn=<AbsBackward0>))

## MSE

```python
torch.nn.MSELoss(size_average=None, reduce=None, reduction='mean')
```

Calcula el error cuadrático

$ l\left(x,y\right) = \left[l_1,...,l_N\right]^T $, donde $l = \left(x_n-y_n\right)^2$

`reduction` usa por defecto ``'mean'``, pero puede también usar ``'sum'`` y ``'none'``. Los parámetros ``size_average`` y ``reduce`` están obsoletos y Pytorch recomienda no usarlos y solo usar ``reduction``

Cuando en ``reduction`` se usa ``'mean'`` se hace una media de todos los errores, cuando se usa ``'sum'`` se hace la suma de todos los errores y cuando se usa ``'none'`` no se hace nada

Vamos a verlo

Creamos lo que sería la predicción de la red neuronal

In [33]:
import torch

preds = torch.rand(3, 5, requires_grad=True)
preds

tensor([[0.5684, 0.4625, 0.5211, 0.9668, 0.8776],
        [0.7379, 0.9137, 0.6533, 0.5459, 0.2191],
        [0.5523, 0.9015, 0.8059, 0.8893, 0.3489]], requires_grad=True)

Creamos lo que sería la verdadera salida

In [34]:
target = torch.rand(3, 5)
target

tensor([[0.8533, 0.8784, 0.0505, 0.9376, 0.2134],
        [0.2214, 0.6986, 0.1518, 0.2798, 0.2936],
        [0.5170, 0.2116, 0.8899, 0.6630, 0.0535]])

Definimos la función de coste con `reduction` con su valor predeterminado, es decir, `mean` y comparamos lo que da la función de coste con hacer nosotros la operación que dice la teoría

In [35]:
loss = torch.nn.MSELoss(size_average=None, reduce=None, reduction='mean') # Predeterminado

loss_fn = loss(preds, target)
my_loss = (abs(preds - target).mean())**2

loss_fn.item(), my_loss.item()

(0.1454271823167801, 0.10110653936862946)

Definimos la función de coste ahora con `reduction` con valor `sum` y comparamos lo que da la función de coste con hacer nosotros la operación que dice la teoría

In [36]:
loss = torch.nn.MSELoss(size_average=None, reduce=None, reduction='sum')

loss_fn = loss(preds, target)
my_loss = ((preds - target)**2).sum()

loss_fn.item(), my_loss.item()

(2.1814076900482178, 2.1814076900482178)

Definimos la función de coste ahora con `reduction` con valor `none` y comparamos lo que da la función de coste con hacer nosotros la operación que dice la teoría

In [37]:
loss = torch.nn.MSELoss(size_average=None, reduce=None, reduction='none')

loss_fn = loss(preds, target)
my_loss = (preds - target)**2

loss_fn, my_loss

(tensor([[0.0812, 0.1730, 0.2215, 0.0009, 0.4411],
         [0.2669, 0.0463, 0.2515, 0.0708, 0.0056],
         [0.0012, 0.4759, 0.0071, 0.0512, 0.0873]], grad_fn=<MseLossBackward0>),
 tensor([[0.0812, 0.1730, 0.2215, 0.0009, 0.4411],
         [0.2669, 0.0463, 0.2515, 0.0708, 0.0056],
         [0.0012, 0.4759, 0.0071, 0.0512, 0.0873]], grad_fn=<PowBackward0>))

## Cross entropy

```python
torch.nn.CrossEntropyLoss(weight=None, size_average=None, ignore_index=- 100, reduce=None, reduction='mean', label_smoothing=0.0)
```

Calcula el error cuadrático

$ l\left(x,y\right) = \left[l_1,...,l_N\right]^T $, donde $l = \left(x_n-y_n\right)^2$

`reduction` usa por defecto ``'mean'``, pero puede también usar ``'sum'`` y ``'none'``. Los parámetros ``size_average`` y ``reduce`` están obsoletos y Pytorch recomienda no usarlos y solo usar ``reduction``

Cuando en ``reduction`` se usa ``'mean'`` se hace una media de todos los errores, cuando se usa ``'sum'`` se hace la suma de todos los errores y cuando se usa ``'none'`` no se hace nada

Vamos a verlo

Creamos lo que sería la predicción de la red neuronal

In [ ]:
import torch

preds = torch.rand(3, 5, requires_grad=True)
preds

tensor([[0.5684, 0.4625, 0.5211, 0.9668, 0.8776],
        [0.7379, 0.9137, 0.6533, 0.5459, 0.2191],
        [0.5523, 0.9015, 0.8059, 0.8893, 0.3489]], requires_grad=True)

Creamos lo que sería la verdadera salida

In [ ]:
target = torch.rand(3, 5)
target

tensor([[0.8533, 0.8784, 0.0505, 0.9376, 0.2134],
        [0.2214, 0.6986, 0.1518, 0.2798, 0.2936],
        [0.5170, 0.2116, 0.8899, 0.6630, 0.0535]])

Definimos la función de coste con `reduction` con su valor predeterminado, es decir, `mean` y comparamos lo que da la función de coste con hacer nosotros la operación que dice la teoría

In [ ]:
loss = torch.nn.MSELoss(size_average=None, reduce=None, reduction='mean') # Predeterminado

loss_fn = loss(preds, target)
my_loss = (abs(preds - target).mean())**2

loss_fn.item(), my_loss.item()

(0.1454271823167801, 0.10110653936862946)

Definimos la función de coste ahora con `reduction` con valor `sum` y comparamos lo que da la función de coste con hacer nosotros la operación que dice la teoría

In [ ]:
loss = torch.nn.MSELoss(size_average=None, reduce=None, reduction='sum')

loss_fn = loss(preds, target)
my_loss = ((preds - target)**2).sum()

loss_fn.item(), my_loss.item()

(2.1814076900482178, 2.1814076900482178)

Definimos la función de coste ahora con `reduction` con valor `none` y comparamos lo que da la función de coste con hacer nosotros la operación que dice la teoría

In [ ]:
loss = torch.nn.MSELoss(size_average=None, reduce=None, reduction='none')

loss_fn = loss(preds, target)
my_loss = (preds - target)**2

loss_fn, my_loss

(tensor([[0.0812, 0.1730, 0.2215, 0.0009, 0.4411],
         [0.2669, 0.0463, 0.2515, 0.0708, 0.0056],
         [0.0012, 0.4759, 0.0071, 0.0512, 0.0873]], grad_fn=<MseLossBackward0>),
 tensor([[0.0812, 0.1730, 0.2215, 0.0009, 0.4411],
         [0.2669, 0.0463, 0.2515, 0.0708, 0.0056],
         [0.0012, 0.4759, 0.0071, 0.0512, 0.0873]], grad_fn=<PowBackward0>))