# Funciones de pérdida

Aunque hay muchas más, vamos a ver las funciones de pérdida incluidas dentro de Pytorch

## L1

```python
torch.nn.L1loss(size_average=None, reduce=None, reduction='mean')
```

Calcula el error absoluto

$ l\left(x,y\right) = \left[l_1,...,l_N\right]^T $, donde $l = \left|x_n-y_n\right|$

`reduction` usa por defecto ``'mean'``, pero puede también usar ``'sum'`` y ``'none'``. Los parámetros ``size_average`` y ``reduce`` están obsoletos y Pytorch recomienda no usarlos y solo usar ``reduction``

Cuando en ``reduction`` se usa ``'mean'`` se hace una media de todos los errores, cuando se usa ``'sum'`` se hace la suma de todos los errores y cuando se usa ``'none'`` no se hace nada

Vamos a verlo

In [1]:
import torch

In [2]:
input = torch.rand(3, 5, requires_grad=True)
input

tensor([[0.1351, 0.0239, 0.1770, 0.1488, 0.9657],
        [0.0284, 0.5864, 0.5616, 0.1387, 0.0609],
        [0.7296, 0.1779, 0.4360, 0.4632, 0.5106]], requires_grad=True)

In [3]:
target = torch.rand(3, 5)
target

tensor([[0.1807, 0.1055, 0.5387, 0.6478, 0.5624],
        [0.2496, 0.3099, 0.8192, 0.1058, 0.4319],
        [0.5870, 0.0883, 0.3144, 0.0442, 0.3914]])

In [4]:
loss = torch.nn.L1Loss(size_average=None, reduce=None, reduction='mean') # Predeterminado

loss_output = loss(input, target)
output = abs(input - target).mean()

output, loss_output

(tensor(0.2295, grad_fn=<MeanBackward0>),
 tensor(0.2295, grad_fn=<L1LossBackward>))

In [8]:
loss = torch.nn.L1Loss(size_average=None, reduce=None, reduction='sum')

loss_output = loss(input, target)
output = abs(input - target).sum()

output, loss_output

(tensor(3.4423, grad_fn=<SumBackward0>),
 tensor(3.4423, grad_fn=<L1LossBackward>))

In [6]:
loss = torch.nn.L1Loss(size_average=None, reduce=None, reduction='none')

loss_output = loss(input, target)
output = abs(input - target)

output, loss_output

(tensor([[0.0456, 0.0816, 0.3617, 0.4990, 0.4033],
         [0.2212, 0.2765, 0.2576, 0.0329, 0.3710],
         [0.1426, 0.0896, 0.1216, 0.4190, 0.1193]], grad_fn=<AbsBackward>),
 tensor([[0.0456, 0.0816, 0.3617, 0.4990, 0.4033],
         [0.2212, 0.2765, 0.2576, 0.0329, 0.3710],
         [0.1426, 0.0896, 0.1216, 0.4190, 0.1193]], grad_fn=<L1LossBackward>))