In [1]:
%matplotlib inline

In [2]:
import torch

# Tensores

## ¿Qué son los tensores?

Los [tensores](https://pytorch.org/docs/stable/tensors.html) son una estructura de datos multidimensional que contiene elementos de un solo tipo de datos.

En PyTorch, se usan tensores para codificar las entradas y salidas de un modelo, así como los parámetros del modelo.

Los tensores son similares a los ndarrays de NumPy, excepto que los tensores pueden ejecutarse en GPU u otros aceleradores de hardware. De hecho, los tensores y las matrices de NumPy a menudo pueden compartir la misma memoria subyacente, lo que elimina la necesidad de copiar datos.

Los tensores también están optimizados para la diferenciación automática (Autograd).

## Tipo de datos de los tensores

Los tensores pueden tener los siguientes tipos de datos con variantes de CPU y GPU

|Tipo de datos|dtype|Tensor de CPU|Tensor de GPU|
|------|------|------|------|
|Punto flotante de 32 bits|``torch.float32`` o ``torch.float``|``torch.FloatTensor``|``torch.cuda.FloatTensor``|
|Punto flotante de 64 bits|``torch.float64`` o ``torch.double``|``torch.DoubleTensor``|``torch.cuda.DoubleTensor``|
|Coma flotante de 16 bits|``torch.float16`` o ``torch.half``|``torch.HalfTensor``|``torch.cuda.HalfTensor``|
|Coma flotante de 16 bits|``torch.bfloat16``|``torch.BFloat16Tensor``|``torch.cuda.BFloat16Tensor``|
|Complejo de 32 bits|``torch.complex32``|||
|Complejo de 64 bits|``torch.complex64``|||
|Complejo de 128 bits|``torch.complex128`` o ``torch.cdouble``|||
|Entero de 8 bits (sin signo)|``torch.uint8``|``torch.ByteTensor``|``torch.cuda.ByteTensor``|
|Entero de 8 bits (con signo)|``torch.int8``|``torch.CharTensor``|``torch.cuda.CharTensor``|
|Entero de 16 bits (con signo)|``torch.int16`` o ``torch.short``|``torch.ShortTensor``|``torch.cuda.ShortTensor``|
|Entero de 32 bits (con signo)|``torch.int32`` o ``torch.int``|``torch.IntTensor``|``torch.cuda.IntTensor``|
|Entero de 64 bits (con signo)|``torch.int64`` o ``torch.long``|``torch.LongTensor``|``torch.cuda.LongTensor``|
|Booleano|``torch.bool``|``torch.BoolTensor``|``torch.cuda.BoolTensor``|
|entero cuantificado de 8 bits (sin signo)|``torch.quint8``|``torch.ByteTensor``|/|
|entero de 8 bits cuantificado (con signo)|``torch.qint8``|``torch.CharTensor``|/|
|entero cuantificado de 32 bits (con signo)|``torch.qfint32``|``torch.IntTensor``|/|
|entero cuantificado de 4 bits (sin signo)|``torch.quint4x2``|torch.ByteTensor|/|

## Inicialización de tensores

Hay muchas maneras de [inicializar un tensor](https://pytorch.org/docs/stable/torch.html#tensor-creation-ops), aquí se muestran algunas

### Directamente con datos

In [14]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

### Desde un array de NumPy


In [18]:
import numpy as np

np_array = np.array(data)
x_np = torch.from_numpy(np_array)

La matriz de Numpy y el Tensor comparten memoria, si se modifica uno se ve reflejado el cambio en el otro

In [19]:
np_array[0, 0] = 99
x_np[1, 1] = 100

print(f"Numpy matrix: \n {np_array} \n")
print(f"Tensor: \n {x_np} \n")

Numpy matrix: 
 [[ 99   2]
 [  3 100]] 

Tensor: 
 tensor([[ 99,   2],
        [  3, 100]], dtype=torch.int32) 



Esto es así, aunque el tensor esté en la GPU

In [20]:
gpu_device = "cuda" if torch.cuda.is_available() else "cpu"
cpu_device = "cpu"

x_np.to(gpu_device)

x_np[1, 1] = 101

print(f"Numpy matrix: \n {np_array} \n")
print(f"Tensor: \n {x_np} \n")

Numpy matrix: 
 [[ 99   2]
 [  3 101]] 

Tensor: 
 tensor([[ 99,   2],
        [  3, 101]], dtype=torch.int32) 



### Desde otro tensor

In [21]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2517, 0.8286],
        [0.0082, 0.3182]]) 



### Con valores aleatorios o constnates

In [22]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4184, 0.1314, 0.7662],
        [0.9868, 0.1299, 0.4800]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Cambiar el tipo de datos de un tensor

Para cambiar el tipo de datos de un tensor hay que usar el atributo ``dtype``

In [26]:
data = [[1, 2],[3, 4]]
x_np_32 = torch.tensor(data, dtype=torch.int32)
x_np_8 = torch.tensor(data, dtype=torch.int8)

print(f"Tensor con datos de tipo entero de 32 bits: \n {x_np_32}")
print(f"Tensor con datos de tipo entero de 8 bits: \n {x_np_8}")

Tensor con datos de tipo entero de 32 bits: 
 tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
Tensor con datos de tipo entero de 8 bits: 
 tensor([[1, 2],
        [3, 4]], dtype=torch.int8)


### Tener el tensor en la GPU o en la CPU

Aunque ya se ha mostrado antes, se puede tener el tensor en la CPU o en la GPU (si se tiene una GPU Nvidia). Al tener el tensor en la GPU se puede aprovechar la capacidad del procesamiento en paralelo

Para pasar el tensr a la GPU se puede usar el parámetro ``device`` o usar el método ``to()``

In [28]:
gpu_device = "cuda" if torch.cuda.is_available() else "cpu"
cpu_device = "cpu"

data = [[1, 2],[3, 4]]
x_np_CPU = torch.tensor(data, device=cpu_device)
x_np_GPU1 = torch.tensor(data, device=gpu_device)
x_np_GPU2 = x_np_CPU.to(gpu_device)

print(f"Tensor en la CPU: \n {x_np_CPU} \n")
print(f"Tensor 1 en la GPU: \n {x_np_GPU1} \n")
print(f"Tensor 2 en la GPU: \n {x_np_GPU2} \n")

Tensor en la CPU: 
 tensor([[1, 2],
        [3, 4]]) 

Tensor 1 en la GPU: 
 tensor([[1, 2],
        [3, 4]], device='cuda:0') 

Tensor 2 en la GPU: 
 tensor([[1, 2],
        [3, 4]], device='cuda:0') 



## Atributos de un tensor

Se pueden obtener los atributos de un tensor, como el tamaño, el tipo y el dispositivo en el que está

In [29]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operaciones con Tensores

Hay más de 100 operaciones con tensores, en este [enlace](https://pytorch.org/docs/stable/torch.html). Cada una de estas operaciones se puede ejecutar en la GPU (normalmente a velocidades más altas que en una CPU).

De forma predeterminada, los tensores se crean en la CPU. Necesitamos mover explícitamente los tensores a la GPU usando el método .to (después de verificar la disponibilidad de la GPU). Hay que tener en cuenta que copiar grandes tensores entre dispositivos puede resultar caro en términos de tiempo y memoria.

In [30]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


Veamos algunas de las operaciones. Al ser muy similares a Numpy, la API de Tensor es muy fácil de usar.

### Indexación y segmentación como en Numpy

In [31]:
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Unión de tensores

Se puede utilizar ``torch.cat`` para concatenar una secuencia de tensores a lo largo de una dimensión determinada. También se puede usar ``torch.stack`` para unir otro tensor y es sutilmente diferente de ``torch.cat``.

In [33]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### Operaciones aritméticas

In [34]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
mat_mult = torch.matmul(tensor, tensor.T, out=y3)

print(f"matrix multiplication: \n {mat_mult} \n")


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
dot_mult = torch.mul(tensor, tensor, out=z3)

print(f"dot multiplication: \n {dot_mult} \n")

matrix multiplication: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

dot multiplication: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



### Tensores de un solo elemento

Se puede tener un tensor de un solo elemento, en este caso, si se quiere convertir a número se puede usar el método `item()`

In [35]:
agg = tensor.sum()
print(f"Tensor de un solo elemento: {agg}, su dimensión es {agg.shape}")

agg_item = agg.item()
print(f"Tensor convertido a número: {agg_item}, es de tipo {type(agg_item)}")

Tensor de un solo elemento: 12.0, su dimensión es torch.Size([])
Tensor convertido a número: 12.0, es de tipo <class 'float'>


### Operaciones in situ

Son operaciones que se realizan sobre el propio elemento, se indican añadiendo un guión bajo `_` al final de la operación. Por ejemplo `x.copy_()` o `x.t_()` modificarán `x`

In [36]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


> Nota: Las operaciones in situ ahorran algo de memoria, pero pueden resultar problemáticas al calcular derivadas debido a una pérdida inmediata del historial. Por tanto, se desaconseja su uso.